<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php else : ?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif; ?>

        <?php if (isset($_SESSION['pdf_url'])): ?>
            <div style="width: 70%">                
                <iframe id="pdf" src="<?php echo $_SESSION["pdf_url"] ?>" style="width:100%; height:950px;" frameborder="0"></iframe>    
            </div>  
        <?php endif; ?>  
        
        <?php if(isset($_SESSION['show_map']) && $_SESSION['show_map'] == '1'): ?>      
            <div style="margin: 20px 0px; width: 70%">
                <h2>Mapa de tiendas</h2>
                <iframe src="https://www.paynet.com.mx/mapa-tiendas/index.html?locationNotAllowed=true" style="border: 1px solid #000; width:100%; height:300px;" frameborder="0"></iframe>                
            </div>    
        <?php endif; ?>

        <?php if (isset($_SESSION['barcode_base64'])): ?>
            <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());
            ?>
            <div class="codi">
                <div class="codi__header">
                    <div class="codi__icon">
                        <img alt="" src="https://i.postimg.cc/HsFprMhV/QR.png" alt="QR" style="width: 40px; height: 40px;">
                        <div class="codi__text codi__text--small">Utilizar la aplicación móvil de banco para hacer el pago de la notificación</div>
                    </div>
                        <div class="codi__subtitle">Pago con CoDi®</div>
                    </div>
                    <div class="codi__content">
                        <figure class="codi__image">
                            <img id="CoDiImage" src="data:image/png;base64, <?=$_SESSION['barcode_base64']?>" alt="QR CoDi®" />
                        </figure>
                        <div class="codi__information">
                            <div class="codi__amount">$<?=number_format($order->getGrandTotal(), 2)?></div>
                            
                            <div class="codi__currency">&nbsp;<?=$order->getBaseCurrencyCode()?></div>
                        </div>
                        <div class="codi__expiration">
                            <div id="CodiTimerTxt" class="codi__text codi__text--timer"></div>
                            <div id="CoDiTimer" class="codi__timer"></div>
                        </div>
                    <div>
                </div>
                <input id="customurl" name="customurl" type="hidden" value="<?php echo $this->getUrl().'openpay/payment/fetchstatus'?>">
                <input id="orderId" name="orderId" type="hidden" value="<?= $block->escapeHtml($block->getOrderId()) ?>">
                <input id="due_date" name="due_date" type="hidden" value="<?=$_SESSION['due_date']?>">
            </div>
        <?php endif; ?>    

    <?php endif; ?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>